{
 "title": "Minecraft - Player",
 "description": "for usage:\nhttps://github.com/heathcliff26/containers/blob/main/apps/minecraft-exporter",
 "tags": [ "minecraft" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values({job=\"minecraft-exporter\"},instance)"
    }
   },
   {
    "name": "player",
    "label": "Player",
    "query": {
     "query": "label_values(minecraft_stat_blocks_mined{instance=~\"$instance\"},player)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Blocks mined",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(minecraft_stat_blocks_mined{instance=~\"$instance\",player=\"$player\"}) by (instance)",
     "legendFormat": "{{block}}"
    }
   ]
  },
  {
   "title": "Items crafted",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(minecraft_stat_blocks_crafted{instance=~\"$instance\",player=\"$player\"}) by (instance)",
     "legendFormat": "{{block}}"
    }
   ]
  },
  {
   "title": "Blocks collected",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(minecraft_stat_blocks_picked_up{instance=~\"$instance\",player=\"$player\"}) by (instance)",
     "legendFormat": "{{block}}"
    }
   ]
  },
  {
   "title": "Deaths",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(minecraft_stat_deaths{instance=~\"$instance\",player=\"$player\",cause=\"minecraft:deaths\"}) by (instance)"
    }
   ]
  },
  {
   "title": "Jumps",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 17, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "minecraft_stat_jumps{instance=~\"$instance\",player=\"$player\"}"
    }
   ]
  },
  {
   "title": "Meters travelled",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "targets": [
    {
     "expr": "minecraft_stat_cm_traveled{instance=~\"$instance\",player=\"$player\"} / 100",
     "legendFormat": "{{  method }}"
    }
   ]
  },
  {
   "title": "Mobs killed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "minecraft_stat_entities_killed{instance=~\"$instance\",player=\"$player\"}",
     "legendFormat": "{{ entity }}"
    }
   ]
  }
 ]
}