{
 "title": "Minecraft - Server",
 "description": "for usage:\nhttps://github.com/heathcliff26/containers/blob/main/apps/minecraft-exporter",
 "tags": [ "minecraft" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values({job=\"minecraft-exporter\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Players Online",
   "type": "table",
   "gridPos": { "h": 18, "w": 3, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max(minecraft_player_online{instance=~\"$instance\"}) by (player, instance)",
     "legendFormat": "{{player}}"
    }
   ]
  },
  {
   "title": "Ticktime",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "forge_ticktime_dim{instance=~\"$instance\"}",
     "legendFormat": "{{dimension_name}} {{instance}} "
    },
    {
     "expr": "forge_ticktime_overall{instance=~\"$instance\"}",
     "legendFormat": "Overall {{instance}} "
    },
    {
     "expr": "minecraft_tick_average{instance=~\"$instance\"}",
     "legendFormat": "Average {{instance}}"
    },
    {
     "expr": "minecraft_tick_percentile{instance=~\"$instance\"}",
     "legendFormat": "P{{percentile}} {{instance}} "
    }
   ]
  },
  {
   "title": "TPS ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "forge_tps_dim{instance=~\"$instance\"}",
     "legendFormat": "{{ dimension_name }}"
    },
    {
     "expr": "forge_tps_overall{instance=~\"$instance\"}",
     "legendFormat": "Overall"
    }
   ]
  },
  {
   "title": "Paper TPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(paper_tps_1m{instance=~\"$instance\"})",
     "legendFormat": "1 Minute"
    },
    {
     "expr": "sum(paper_tps_5m{instance=~\"$instance\"})",
     "legendFormat": "5 Minute"
    },
    {
     "expr": "sum(paper_tps_15m{instance=~\"$instance\"})",
     "legendFormat": "15 Minute"
    }
   ]
  },
  {
   "title": "Entities Loaded",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 3, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "forge_entity_count{instance=~\"$instance\"}",
     "legendFormat": "{{ entity }}"
    }
   ]
  },
  {
   "title": "Play Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "minecraft_stat_playtime{instance=~\"$instance\"} / 20",
     "legendFormat": "{{ player }}"
    }
   ]
  },
  {
   "title": "Dynmap Tile render Statistics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(dynmap_tile_render_stat{instance=~\"$instance\"}) by (type)",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Score",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "minecraft_stat_score{instance=~\"$instance\"}",
     "legendFormat": "{{ player }}"
    }
   ]
  },
  {
   "title": "Dynmap Chunk loading duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "dynmap_chunk_loading_duration{instance=~\"$instance\"}",
     "legendFormat": "{{ type }}"
    }
   ]
  }
 ]
}